# Default values for kiva-ui service.

image:
  repository: kiva/ui
  tag: "" # Expected be set by Jenkins
  pullPolicy: Always

imagePullSecretName: marketplace-regcred

deployenv:
  environment: "" # set either by jenkins or manually

replicaCount: 2

strategy:
  type: "RollingUpdate"
