language: node_js
matrix:
  fast_finish: true
  include:
    - node_js: '8'
    - node_js: 'node'
      if: branch = master
branches:
  only:
    - master
    - /^release-.*$/
before_install:
  - npm install -g npm@5.7
  - npm install -g greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload
  - cat test/unit/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
