language: node_js
cache:
  npm: true
  directories:
    - ~/.cache
addons:
  apt:
    packages:
    - libgconf-2-4
matrix:
  fast_finish: true
  include:
    - node_js: '12.14'
    - node_js: 'node'
      if: head_branch = master
  allow_failures:
    - node_js: 'node'
branches:
  only:
    - master
    - /^release-.*$/
after_script:
  - cat test/unit/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
