# Default values for kiva-ui service.

image:
  repository: kiva/ui
  tag: "" # Expected be set by Jenkins
  pullPolicy: Always

deployenv:
  environment: "" # set either by jenkins or manually

replicaCount: 2

strategy:
  type: "RollingUpdate"

service:
  type: ClusterIP
  port: 443
  containerPort: 8888
  targetPort: 8888
  portName: "https"


ingress:
  enabled: true
  name: "kiva-ui-ingress"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx-ingress-external
    kubernetes.io/ingress.ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  host: "ui-dev.dk1.kiva.org"
  spec:
    rules:
      - host: "ui-dev.dk1.kiva.org"
        http:
          paths:
          - backend:
              serviceName: "kiva-ui"
              servicePort: 443
            path: /
  tls:
    - hosts:
      - ui-dev.dk1.kiva.org
      secretName: "kiva-ui-tls"
