# Values for kiva-ui Dev deployment
# - refer to /deploy/charts/values.yaml for defaults and commentary

image:
  repository: kiva/ui
  tag: "" # Expected be set by Jenkins
  pullPolicy: Always

deployenv:
  environment: "k8sdev" # injected into deployment template

secretName: kiva-ui

service:
  type: ClusterIP
  port: 8888
  portName: &servicePortName "http"

resources:
  requests:
    cpu: 50m
    memory: 256Mi
  limits:
    cpu: 200m
    memory: 400Mi

replicaCount: 1
minReplicas: 1
maxReplicas: 4

metrics:
  name: memory
  target:
    type: AverageValue
    averageValue: 270Mi

ingress:
  host: "ui-dev.dk1.kiva.org"
  spec:
    rules:
      - host: "ui-dev.dk1.kiva.org"
        http:
          paths:
          - backend:
              serviceName: "kiva-ui"
              servicePort: *servicePortName
            path: /
  tls:
    - hosts:
      - ui-dev.dk1.kiva.org
      secretName: "kiva-ui-tls"

configmap:
  data:
  - key: DD_TRACE_GLOBAL_TAGS
    value: "env:dev,app:kiva-ui"
  - key: DD_ENV
    value: "dev"
