apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ui-helm.name" . }}
    helm.sh/chart: {{ include "ui-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- range .Values.configmap.all }}
    {{ .key }}: "{{ .value }}"
    {{- end }}
  {{- range .Values.configmap.data }}
    {{ .key }}: "{{ .value }}"
    {{- end }}
