apiVersion: v1
kind: Service
metadata:
  name: {{ include "ui-helm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ui-helm.name" . }}
    helm.sh/chart: {{ include "ui-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    name: {{ .Values.service.portName }}
  selector:
    app.kubernetes.io/name: {{ include "ui-helm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

