# This is a basic workflow to help you get started with Actions

name: Deploy Storybook to GitHub Pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
#    push:
#      branches: [ master ]
  schedule:
    - cron:  '30 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - run: npm install
      - run: npm run build-storybook

      - uses: appleboy/gh-pages-action@v0.0.2
        with:
          remote_url: https://github.com:kiva/ui.git
          target_branch: master
          pages_directory: storybook-static
          target_directory: storybook
        
